# Site settings
title: 张泽阳的个人博客
email:  zzyyzz1992@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  张泽阳的博客
baseurl: "" # the subpath of your site, e.g. /blog/
#url: "http://yansu.org" # the base hostname & protocol for your site
rss_url: /pages/feed.xml

# Sidebar filter
# Choose 'tag' or 'category' as filter in sidebar.
filter: 'category'

# Social account
# twitter: masonzzyyzz1992
# weibo:    ID
github: zzyyzz1992
# codepen:  username
# dribbble: username

# avatar头像及Favicon
# avatar: http://7u2ho6.com1.z0.glb.clouddn.com/site-avatar.png
# favicon: http://7u2ho6.com1.z0.glb.clouddn.com/site-favicon.ico

# disqus 设置
disqus:
  shortname: zzyyzz1992-zh

# google analytics 设置
# ga:
#   id: UA-54767140-1
#   url: yansu.org

# Build settings
permalink: /:year/:month/:day/:title.html
markdown: kramdown
highlighter: rouge
sass:
  style: compressed
